using Microsoft.EntityFrameworkCore.Migrations;

namespace GDC_Inventory_Database.Migrations
{
    public partial class Init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Items",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SoupSpoons = table.Column<string>(nullable: true),
                    SteakKnives = table.Column<string>(nullable: true),
                    DessertSpoons = table.Column<string>(nullable: true),
                    DemiTassSpoonsO = table.Column<string>(nullable: true),
                    DemiTassSpoonN = table.Column<string>(nullable: true),
                    SaladForks = table.Column<string>(nullable: true),
                    DinnerForks = table.Column<string>(nullable: true),
                    DinnerKnives = table.Column<string>(nullable: true),
                    TeaSpoons = table.Column<string>(nullable: true),
                    ButterKnives = table.Column<string>(nullable: true),
                    LongHandleSpoonsO = table.Column<string>(nullable: true),
                    LongHandleSpoonsN = table.Column<string>(nullable: true),
                    TongsNStyle = table.Column<string>(nullable: true),
                    TongsOStyle = table.Column<string>(nullable: true),
                    TongsSmallO = table.Column<string>(nullable: true),
                    TongsSmallN = table.Column<string>(nullable: true),
                    LadlesLargeO = table.Column<string>(nullable: true),
                    LadlesLargeN = table.Column<string>(nullable: true),
                    LadlesSmallSS = table.Column<string>(nullable: true),
                    PieSpatula = table.Column<string>(nullable: true),
                    SeaShellTongs = table.Column<string>(nullable: true),
                    CocktailForks = table.Column<string>(nullable: true),
                    FishSpoonsSmall = table.Column<string>(nullable: true),
                    BasePlates12 = table.Column<string>(nullable: true),
                    DinnerPlates11N = table.Column<string>(nullable: true),
                    DinnerPlates11O = table.Column<string>(nullable: true),
                    SaladPlates9N = table.Column<string>(nullable: true),
                    SaladPlates9O = table.Column<string>(nullable: true),
                    BBPlates6N = table.Column<string>(nullable: true),
                    BBPlates6O = table.Column<string>(nullable: true),
                    CoffeeSaucersN = table.Column<string>(nullable: true),
                    CoffeeSaucersO = table.Column<string>(nullable: true),
                    CoffeeCupsLG = table.Column<string>(nullable: true),
                    CoffeeCupsSmallO = table.Column<string>(nullable: true),
                    CoffeeMugsLarge = table.Column<string>(nullable: true),
                    CoffeeMugsSmall = table.Column<string>(nullable: true),
                    SoupCups = table.Column<string>(nullable: true),
                    PlateCovers = table.Column<string>(nullable: true),
                    CoffeePots = table.Column<string>(nullable: true),
                    WaterPitchers = table.Column<string>(nullable: true),
                    Creamers = table.Column<string>(nullable: true),
                    CreamersSS = table.Column<string>(nullable: true),
                    GlassesShooters = table.Column<string>(nullable: true),
                    GlassesShootersTall = table.Column<string>(nullable: true),
                    GlassesBeverage = table.Column<string>(nullable: true),
                    GlassesRocks = table.Column<string>(nullable: true),
                    GlassesWaterBanquets = table.Column<string>(nullable: true),
                    GlassesWater8oz = table.Column<string>(nullable: true),
                    GlassesWineBanquets = table.Column<string>(nullable: true),
                    GlassesWineLargeRedCafeAdelaide = table.Column<string>(nullable: true),
                    GlassesWineWhiteCafeAdelaide = table.Column<string>(nullable: true),
                    GlassesWineRoomServiceO = table.Column<string>(nullable: true),
                    GlassesChampagne = table.Column<string>(nullable: true),
                    GlassesMartini = table.Column<string>(nullable: true),
                    GlassesMartiniSmall = table.Column<string>(nullable: true),
                    GlassesMartiniwBall = table.Column<string>(nullable: true),
                    GlassesTomCollins = table.Column<string>(nullable: true),
                    ThermosCoffeePotSSSmall = table.Column<string>(nullable: true),
                    ThermosCoffeePotSSLarge = table.Column<string>(nullable: true),
                    PunchBowlSmall = table.Column<string>(nullable: true),
                    PunchBowlLarge = table.Column<string>(nullable: true),
                    HeatLamps = table.Column<string>(nullable: true),
                    ChaffingDishLargeBanquets = table.Column<string>(nullable: true),
                    ChaffingDishSmallBanquets = table.Column<string>(nullable: true),
                    MarmitesSmallBanquets = table.Column<string>(nullable: true),
                    DemiTassCups = table.Column<string>(nullable: true),
                    DemiTassSaucers = table.Column<string>(nullable: true),
                    CremeBruleeDishVertexThreePointFive = table.Column<string>(nullable: true),
                    PotCastIron = table.Column<string>(nullable: true),
                    BlackSoupStubsSmall = table.Column<string>(nullable: true),
                    PotGreenIronLarge = table.Column<string>(nullable: true),
                    PotGreenIronMedium = table.Column<string>(nullable: true),
                    PotGreenIronOval = table.Column<string>(nullable: true),
                    PotBlueIronLarge = table.Column<string>(nullable: true),
                    PotBlueIronMedium = table.Column<string>(nullable: true),
                    PotBlueIronOval = table.Column<string>(nullable: true),
                    PotYellowIronLarge = table.Column<string>(nullable: true),
                    PotYellowIronMedium = table.Column<string>(nullable: true),
                    PotYellowIronOval = table.Column<string>(nullable: true),
                    PotBlackIronLarge = table.Column<string>(nullable: true),
                    PotBlackIronMedium = table.Column<string>(nullable: true),
                    PotBlackIronOval = table.Column<string>(nullable: true),
                    PotRedIronLarge = table.Column<string>(nullable: true),
                    PotRedIronMedium = table.Column<string>(nullable: true),
                    PotRedIronOval = table.Column<string>(nullable: true),
                    WocBlack = table.Column<string>(nullable: true),
                    Bricks = table.Column<string>(nullable: true),
                    BentoBoxesAndRedPlates = table.Column<string>(nullable: true),
                    IceGlo = table.Column<string>(nullable: true),
                    IceGlo52 = table.Column<string>(nullable: true),
                    IceGlo32AndAHalf = table.Column<string>(nullable: true),
                    Mirror101By70 = table.Column<string>(nullable: true),
                    Mirror80By80 = table.Column<string>(nullable: true),
                    SilverTrayRoundLarge = table.Column<string>(nullable: true),
                    UnderlinersSilverTrayLarge = table.Column<string>(nullable: true),
                    UnderlinersSilverTrayMedium = table.Column<string>(nullable: true),
                    UnderlinersSilverTraySmall = table.Column<string>(nullable: true),
                    UnderlinersMarmitesSilverTray = table.Column<string>(nullable: true),
                    PlatesYellowGlassFiveAndAHalfLarge = table.Column<string>(nullable: true),
                    PlatesYellowGlassThreePointThreeSmall = table.Column<string>(nullable: true),
                    PlatesBlueGlassFiveAndAHalfLarge = table.Column<string>(nullable: true),
                    PlatesBlueGlassThreePointThreeSmall = table.Column<string>(nullable: true),
                    PlatesGreenGlassFiveAndAHalfLarge = table.Column<string>(nullable: true),
                    PlatesGreenGlassThreePointThreeSmall = table.Column<string>(nullable: true),
                    PlatesGlassFiveAndAHalfLarge = table.Column<string>(nullable: true),
                    PlatesGlassThreePointThreeSmall = table.Column<string>(nullable: true),
                    UrnsCoffeeLarge = table.Column<string>(nullable: true),
                    UrnsCoffeeMedium = table.Column<string>(nullable: true),
                    UrnsCoffeeSmall = table.Column<string>(nullable: true),
                    ButterDishesCafeAdelaide = table.Column<string>(nullable: true),
                    Remekins3CafeAdelaide = table.Column<string>(nullable: true),
                    SoupCupsCAandSS = table.Column<string>(nullable: true),
                    WhiteCeramicSpoon = table.Column<string>(nullable: true),
                    SmallChampagneCoup = table.Column<string>(nullable: true),
                    PafeyGlassesInStorage = table.Column<string>(nullable: true),
                    TeaPotsSS = table.Column<string>(nullable: true),
                    LargeWhiteFootBalls = table.Column<string>(nullable: true),
                    MediumWhiteFootBalls = table.Column<string>(nullable: true),
                    SmallWhiteFootBalls = table.Column<string>(nullable: true),
                    WhiteRectangularPlates = table.Column<string>(nullable: true),
                    WhiteSquarPlates = table.Column<string>(nullable: true),
                    LargeEyeBallPlates = table.Column<string>(nullable: true),
                    SSteelCharterPlateUnderlinerO = table.Column<string>(nullable: true),
                    AuJusLadelO = table.Column<string>(nullable: true),
                    LargeRoundSilverTraysO = table.Column<string>(nullable: true),
                    SaladTongs = table.Column<string>(nullable: true),
                    LargeDessertSpoonsForDressing = table.Column<string>(nullable: true),
                    BQSSteelGooseNecks = table.Column<string>(nullable: true),
                    TenOZWaterGlassForRoomServiceN = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Items", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Items");
        }
    }
}
